Make dna2json browser-friendly
genomejs/dna2json pull request #26
Opened 2017-07-07 08:26 UTC by zhaofengli

This commit removes `require-dir` which depends on `fs`.

The parser list needs to hard-coded, but it makes things easier to track. Any thoughts?

2017-07-07 15:01 UTC, yocontra requested changes

2017-07-07 15:01 UTC, contra commented on index.js
> +var requireDir = require('require-directory');
left one still

2017-07-07 15:02 UTC, contra commented
Good idea 👍

2017-07-07 18:29 UTC, zhaofengli commented
Oops, wasn't quite awake when making this patch :fearful: Fixed.

2017-07-07 18:36 UTC, merged

2017-07-17 09:30 UTC, zhaofengli commented
In case you are interested, I made [zhaofengli/snappy](https://github.com/zhaofengli/snappy) ([live version](https://zhaofengli.github.io/snappy)). It's completely static, with all processing done client-side. Thanks for all your work here!

2017-07-17 13:57 UTC, contra commented
@zhaofengli Sweet! Does it let you pull your file back out as SNP-JSON? If so, feel free to add it to the readme as a web version.

2017-07-17 18:33 UTC, zhaofengli commented
@contra Great idea! It doesn't at the moment, but should be easy to add. I'm actually considering adding a serializer to convert SNP-JSON back to 23andMe/AncestryDNA formats to dna2json, so files merged in Snappy can be useful for other analysis tools.

I'm thinking about how to contribute some of the code back to genome.js. Snappy has a [parser](https://github.com/zhaofengli/snappy/blob/master/src/snappy/gs-criteria.pegjs) that understands the [genoset criteria syntax](https://www.snpedia.com/index.php/Criteria_syntax), enabling it to use the full set of genosets (including recursive ones depending on other genosets) on SNPedia by [transforming them to gql queries](https://github.com/zhaofengli/snappy/blob/master/src/snappy/Utils.js#L7). However, it depends on a large JSON ([~110K](https://github.com/zhaofengli/snappy/blob/master/data/genosets.json)) which is undesirable if you only want to use a single genoset. Also, the genosets *will still not match correctly without considering orientations* (Snappy has `normalizedSnps`; see below). I'm not sure if this is considered in the genoset modules on NPM right now.

Additionally, gql's `exact()` should match single letter genotypes against their two-letter counterparts (e.g. "A" == "AA"). AFAIK only 23andMe reports single letter genotypes in raw data, and this will cause inconsistencies when querying data from other vendors. Snappy hacks around this by converting all genotypes to two letters, so that gql can match correctly using SNPedia genosets.

Snappy also deals with orientations and insertions (in a hopefully correct way). For example, `file.normalizedSnps.rs1000283.genotype` will give you `CC`, when the raw data reports `GG`, as [the `StabilizedOrientation` field on SNPedia](https://www.snpedia.com/index.php/rs1000283) is minus. Regarding insertions, `I-` reported for [rs5030655](https://www.snpedia.com/index.php/rs5030655) will be resolved to `rs5030655(-;T)` on SNPedia (also see [this discussion](https://www.snpedia.com/index.php/Talk:Rs5030655)), and `Genotypes.get('rs332', 'II')` will return a Promise that eventually rejects, because [`II` is ambigous](https://www.snpedia.com/index.php/rs332). At this time, I don't see an efficient way to automatically handle those in genome.js, as we can't assume the original orientations of supplied data (we can for 23andMe and AncestryDNA, which always reports on the forward strand; FamilyTreeDNA data from a casual look does this too, but it [didn't](http://forums.familytreedna.com/showthread.php?t=28483) back then), and that would require a list of affected SNPs ([a monsterous ~450K JSON](https://github.com/zhaofengli/snappy/blob/master/data/minusorientationsnps.json); but luckily you have gzip).

Any thoughts? Thanks!

2017-07-17 18:33 UTC, zhaofengli commented
By the way, the goal of Snappy is to fully emulate Promethease, running entirely in the browser.

2017-07-17 19:03 UTC, contra commented
@zhaofengli For the JSON could make a repo and take the approach of https://github.com/contra/boundaries (individual json files)

All the rest sounds great, looking forward to any changes you want to bring back.

If you want to make any repos on the genome.js org let me know and I'll add you as a member.